name: Python Code Checks

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install uv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r <(uv pip compile --all-extras pyproject.toml)
          uv pip install ruff tox

      - name: Run Ruff (PEP 8 Formatting)
        run: |
          source .venv/bin/activate
          ruff format --check --diff

      - name: Run Ruff (Linting + Docstrings)
        run: |
          source .venv/bin/activate
          ruff check

